"""Configuration-driven executor for reusable task primitives."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from .primitives import change_gripper, hold_pose, move_arm, move_base
from .state import TaskState


ActionHandler = Callable[..., list[TaskState]]


DEFAULT_ACTIONS: dict[str, ActionHandler] = {
    "hold_pose": hold_pose,
    "move_base": move_base,
    "move_arm": move_arm,
    "change_gripper": change_gripper,
}


def load_task_config(path: str | Path) -> dict[str, Any]:
    """Load a YAML task configuration with safe YAML parsing."""

    config_path = Path(path).expanduser().resolve()
    with config_path.open("r", encoding="utf-8") as stream:
        config = yaml.safe_load(stream)
    if not isinstance(config, dict):
        raise ValueError("task configuration must be a YAML mapping")
    return config


def state_from_config(raw_state: Mapping[str, Any]) -> TaskState:
    """Build the initial TaskState from a configuration mapping."""

    required = {"base", "arm_qpos", "gripper"}
    missing = sorted(required - set(raw_state))
    if missing:
        raise ValueError(
            "initial_state is missing required fields: "
            + ", ".join(missing)
        )
    return TaskState(
        phase=raw_state.get("phase", "initial"),
        base=raw_state["base"],
        arm_qpos=raw_state["arm_qpos"],
        gripper=raw_state["gripper"],
        object_joints=raw_state.get("object_joints", {}),
        active_target=raw_state.get("active_target"),
    )


@dataclass(frozen=True, slots=True)
class ActionRange:
    """Inclusive trajectory-index range generated by one configured action."""

    action_index: int
    action: str
    phase: str
    start_state_index: int
    end_state_index: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "action_index": self.action_index,
            "action": self.action,
            "phase": self.phase,
            "start_state_index": self.start_state_index,
            "end_state_index": self.end_state_index,
        }


@dataclass(frozen=True, slots=True)
class ExecutionResult:
    """Trajectory and action boundaries produced from one task config."""

    task_name: str
    states: tuple[TaskState, ...]
    action_ranges: tuple[ActionRange, ...]

    @property
    def final_state(self) -> TaskState:
        return self.states[-1]

    def to_dict(self) -> dict[str, Any]:
        return {
            "task_name": self.task_name,
            "state_count": len(self.states),
            "states": [state.to_dict() for state in self.states],
            "action_ranges": [
                action_range.to_dict()
                for action_range in self.action_ranges
            ],
        }


class TaskExecutor:
    """Execute configured actions using a reusable action registry."""

    def __init__(
        self,
        actions: Mapping[str, ActionHandler] | None = None,
    ) -> None:
        self._actions = dict(DEFAULT_ACTIONS if actions is None else actions)
        if not self._actions:
            raise ValueError("the action registry cannot be empty")

    @property
    def action_names(self) -> tuple[str, ...]:
        return tuple(sorted(self._actions))

    def register_action(
        self,
        name: str,
        handler: ActionHandler,
        *,
        replace: bool = False,
    ) -> None:
        action_name = str(name).strip()
        if not action_name:
            raise ValueError("action name must be non-empty")
        if action_name in self._actions and not replace:
            raise ValueError(f"action {action_name!r} is already registered")
        if not callable(handler):
            raise TypeError("action handler must be callable")
        self._actions[action_name] = handler

    def execute(self, config: Mapping[str, Any]) -> ExecutionResult:
        """Build a trajectory by executing actions in configuration order."""

        task_name = str(config.get("task_name", "unnamed_task")).strip()
        if not task_name:
            raise ValueError("task_name must be non-empty")

        raw_initial = config.get("initial_state")
        if not isinstance(raw_initial, Mapping):
            raise ValueError("initial_state must be a mapping")
        current = state_from_config(raw_initial)

        raw_actions = config.get("actions")
        if not isinstance(raw_actions, list) or not raw_actions:
            raise ValueError("actions must be a non-empty list")

        states = [current]
        ranges: list[ActionRange] = []
        for action_index, raw_action in enumerate(raw_actions):
            if not isinstance(raw_action, Mapping):
                raise ValueError(
                    f"actions[{action_index}] must be a mapping"
                )
            parameters = dict(raw_action)
            action_name = str(parameters.pop("action", "")).strip()
            if action_name not in self._actions:
                available = ", ".join(self.action_names)
                raise ValueError(
                    f"unknown action {action_name!r} at index {action_index}; "
                    f"available actions: {available}"
                )

            handler = self._actions[action_name]
            try:
                generated = handler(current, **parameters)
            except (TypeError, ValueError) as error:
                raise ValueError(
                    f"action {action_index} ({action_name}) failed: {error}"
                ) from error

            if not generated:
                raise ValueError(
                    f"action {action_index} ({action_name}) "
                    "generated no states"
                )
            if not all(isinstance(state, TaskState) for state in generated):
                raise TypeError(
                    f"action {action_index} ({action_name}) returned "
                    "a non-TaskState value"
                )

            start_index = len(states)
            states.extend(generated)
            current = generated[-1]
            ranges.append(
                ActionRange(
                    action_index=action_index,
                    action=action_name,
                    phase=current.phase,
                    start_state_index=start_index,
                    end_state_index=len(states) - 1,
                )
            )

        return ExecutionResult(
            task_name=task_name,
            states=tuple(states),
            action_ranges=tuple(ranges),
        )
